feat: Updated .github/workflows/cla.yml

diff --git a/.github/workflows/cla.yml b/.github/workflows/cla.yml
--- a/.github/workflows/cla.yml
+++ b/.github/workflows/cla.yml
@@ -39,9 +39,17 @@ jobs:
   CLAAssistant:
     runs-on: ubuntu-latest
     steps:
+      - name: "Debug Start Message"
+        run: echo 'Job starting...'
       - name: "CLA Assistant"
         if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
-        uses: contributor-assistant/github-action@v2.3.1
+        run: |
+          echo 'Trying CLA Assistant step...'
+          if ! contributor-assistant/github-action@v2.3.1; then
+            echo '::error::Error in CLA Assistant step'
+          fi
+      - name: "Debug End Message"
+        run: echo 'Job finished.'
         env:
           GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
           PERSONAL_ACCESS_TOKEN: ${{ secrets.REDBOT_GITHUB_TOKEN }}
